version: '3.4'
services:
  database:
    image: postgres
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - database

  api:
    build:
      context: .
      target: development
    depends_on:
      - database
    env_file: .env
    ports:
      - 3333:3333

volumes:
  database:
