version: '3.4'
services:
  database:
    image: postgres
    container_name: database
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  api:
    container_name: api
    build:
      context: .
      target: development
    depends_on:
      - database
      - keycloak
    env_file: .env
    ports:
      - 3333:3333
    volumes:
      - ./:/app

  keycloak-database:
    container_name: keycloak-database
    image: postgres
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
      POSTGRES_USER: ${KEYCLOAK_DATABASE_USER}
      POSTGRES_DB: ${KEYCLOAK_DATABASE_NAME}
    ports:
      - 5434:5432
    volumes:
      - keycloak-postgres:/var/lib/postgresql/data

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    env_file: .env
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: ${KEYCLOAK_DATABASE_HOST}
      DB_DATABASE: ${KEYCLOAK_DATABASE_NAME}
      DB_USER: ${KEYCLOAK_DATABASE_USER}
      DB_SCHEMA: public
      DB_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm.json
    volumes:
      - ./.docker/keycloak/imports:/opt/jboss/keycloak/imports
    depends_on:
      - keycloak-database
    ports:
      - 8080:8080

volumes:
  postgres:
  keycloak-postgres:
