version: '3.4'
services:
  database:
    image: postgres
    container_name: 'flashcard_db'
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres:/var/lib/postgresql/data

  api:
    container_name: 'flashcard_api'
    build:
      context: .
      target: development
    depends_on:
      - database
    env_file: .env
    ports:
      - 3333:3333
    volumes:
      - ./:/app

volumes:
  postgres:
